# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointCorrection
                                 A QGIS plugin
 Following corrections made to interpretation shape subclass number, interpretation fields are updated and correction field in point file is updated with new value and accuracy csv updated.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-14
        copyright            : (C) 2019 by David Kerr
        email                : dk@tcarta.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointCorrection class from file PointCorrection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .point_correction import PointCorrection
    return PointCorrection(iface)
